apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: "2020-09-30T09:03:24Z"
  name: minio-amundsen-loader
  namespace: seldon
  resourceVersion: "7409973"
  selfLink: /apis/batch/v1beta1/namespaces/seldon/cronjobs/minio-amundsen-loader
  uid: d1020f7e-67bc-4165-bff8-7bf357b1efa0
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: minio-amundsen-loader
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: simplejob
            imagePullPolicy: IfNotPresent
            name: minio-amundsen-loader
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/15 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
