apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: minio-amundsen-loader
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: minio-amundsen-loader
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: minio-amundsen-loader
            imagePullPolicy: IfNotPresent
            name: minio-amundsen-loader
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/15 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
